name: Create Pull Request

on:
  push:
    branches: [main]
jobs:
  create-release:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        run: echo ${{ github.ref }}
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm
        env:
          npm_config_registry: https://registry.npmjs.org/
      - run: pnpm install --frozen-lockfile
      - run: pnpm install @changesets/cli
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:deploy
          createGithubReleases: true
