name: Publish Release

on:
  push:
    branches:
      - main # Este evento se disparará después de un merge en la rama principal
  pull_request:
    types:
      - closed # Puedes mantener esta parte también para verificar el cierre de un PR

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.pull_request.merged == true }}
    name: Publish to npm and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Asegúrate de obtener todo el historial de Git

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Setup pnpm
        run: npm install -g pnpm # Instala pnpm globalmente

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release
        run: pnpm changeset:release

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }} # Usar el commit hash como tag
          release_name: Release ${{ github.sha }}
          body: |
            This release includes:
            - All changes from PR: ${{ github.event.pull_request.html_url }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
