name: Publish Release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write # Permite escribir contenido en el repositorio
  packages: write # Permite publicar en GitHub Packages (opcional)
  pull-requests: write # Permite manejar PRs si es necesario

jobs:
  publish:
    if: ${{ github.event.pull_request.merged == true }}
    name: Publish to npm and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release
        run: pnpm changeset:release # Lanza el comando para realizar la versión final

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            This release includes:
            - All changes from PR: ${{ github.event.pull_request.html_url }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
