name: Publish Release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.pull_request.merged == true }}
    name: Publish to npm and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Setup pnpm
        run: npm install -g pnpm # Instala `pnpm` globalmente para que esté disponible en el entorno

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release
        run: pnpm changeset:release

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.pull_request.head.ref }}
          release_name: Release ${{ github.event.pull_request.head.ref }}
          body: |
            This release includes:
            - All changes from PR: ${{ github.event.pull_request.html_url }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
